### ISSUE TITLE
Image.ANTIALIAS in PIL

### ISSUE THREAD

**Issue by kc29wang** [dannydeezy/mosaics#5]
_Processing main image...
Traceback (most recent call last):
  File "C:\Users\c29wa\mosaics\mosaic.py", line 501, in <module>
    mosaic(source_image, tile_dir_list, image_title, slug_names)
  File "C:\Users\c29wa\mosaics\mosaic.py", line 473, in mosaic
    image_data = TargetImage(img_path).get_data()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c29wa\mosaics\mosaic.py", line 94, in get_data
    large_img = img.resize((w, h), Image.ANTIALIAS)
                                   ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'_

It looks like the latest version of pillow (PIL) deprecated Image.ANTIALIAS.

Please either downgrade your PIL version, or remove all "Image.ANTIALIA" from mosaic.py file.

**Comment by dannydeezy** [comment]
thank you @c29wang  - i just fixed it by removing the `Image.ANTIALIAS` option - it doesn't seem necessary anyway
